version: '3.1'

services:

  php:
    container_name: ${CONTAINER_WORDPRESS_NAME}
    build:
      context: ./php
    ports:
      - ${APP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_BD_NAME}
      WORDPRESS_DB_USER: ${BD_USER}
      WORDPRESS_DB_PASSWORD: ${BD_PASS}
      WORDPRESS_DB_NAME: ${BD_NAME}
      WORDPRESS_DEBUG: ${APP_DEBUG}
    volumes:
      - ${APP_DIR}:/var/www/html
      - ./usr/local/etc/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    links:
        - db

  db:
    container_name: ${CONTAINER_BD_NAME}
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${BD_NAME}
      MYSQL_USER: ${BD_USER}
      MYSQL_PASSWORD: ${BD_PASS}
      MYSQL_ROOT_PASSWORD: ${BD_PASS_ROOT}
    volumes:
      - db_wordpress:/var/lib/mysql
    ports:
        - 3306:3306
volumes:
  db_wordpress: